### ISSUE TITLE
Task bar alert doesn't show

### ISSUE THREAD

**Issue by ghost** [getkey/discreet-flat#1]
When an application is set to alert the user via the task bar (aka Windows List), it doesn't show. Instead, it doesn't do anything. Nothing is showed. Here is an example of the Arc theme with task bar alerts:
![97f12](https://cloud.githubusercontent.com/assets/23224476/25545720/b5243c0a-2c25-11e7-88f2-9bff0ed3d97a.png)
And here is an example of what Discreet Flat looks like during a task bar alert:
![dd880](https://cloud.githubusercontent.com/assets/23224476/25545742/c4d8d0d4-2c25-11e7-9244-c953bba3fa9f.png)
I really enjoy this theme. I am glad someone put the effort to make this theme. It is perfect for my taste. But the task bar alert is an issue.

**Comment by getkey** [comment]
Thanks for the detailed bug report, I'm happy you like it. I fixed the bug, but the way Cinnamon themes are uploaded has changed and I need to look into how it works. I'll do that later this afternoon.

**Comment by ghost** [comment]
I understand. Take your time. I'm glad you fixed the issue.

**Comment by getkey** [comment]
It's out of my hands now, it will be available as soon as the Linux Mint devs get linuxmint/cinnamon-spices-themes#152 merged. :-)

**Comment by ghost** [comment]
Thank you so much. I am currently using your build as of right now and it seems to be working just fine. I now have task bar alerts and they work perfectly. Thank you for your work.
